export const ADD_TO_CART = "ADD_TO_CART";
export const DELETE_FROM_CART = "DELETE_FROM_CART";

export const LOAD_PRODUCTS_START = "LOAD_PRODUCTS_START";
export const LOAD_PRODUCTS_END = "LOAD_PRODUCTS_END";

export const ERROR_WHILE_FETCHING = "ERROR_WHILE_FETCHING";