export const LOAD_PRODUCTS_START = "LOAD_PRODUCTS_START";
export const LOAD_PRODUCTS_END = "LOAD_PRODUCTS_END";

export const ADD_TO_CART = "ADD_TO_CART";
export const ADD_TO_CART_START = "ADD_TO_CART_START";
export const LOAD_CART = "LOAD_CART";
export const UPDATE_CART = "UPDATE_CART";
export const DELETE_FROM_CART = "DELETE_FROM_CART";
export const INC_PROD_QUANTITY = "INC_PROD_QUANTITY";
export const DEC_PROD_QUANTITY = "DEC_PROD_QUANTITY";

export const ERROR_WHILE_FETCHING = "ERROR_WHILE_FETCHING";